name: Build

on:
  push:
    branches: [ $default-branch, "master" ]
  pull_request:
    branches: [ $default-branch, "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name : Setup test
      run: 'echo "$PRIVATE_KEY" > gha-token-test.private-key.pem'
      shell: bash
      env:
        PRIVATE_KEY: ${{secrets.PRIVATE_KEY}}

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Lint
      uses: golangci/golangci-lint-action@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
